## bisenetv2
cfg = dict(
    model_type='bisenetv2',
    n_cats=4,
    num_aux_heads=4,
    lr_start=1e-2,
    weight_decay=1e-4,
    warmup_iters=500,
    max_iter=20000,
    dataset='CustomerDataset',
    im_root='D:/dataset/edge',
    train_im_anns='D:/dataset/edge/train.txt',
    val_im_anns='D:/dataset/edge/val.txt',
    scales=[0.75, 2.],
    cropsize=[320, 320],
    eval_crop=[320, 320],
    eval_scales=[0.5, 0.75, 1, 1.25, 1.5, 1.75],
    ims_per_gpu=16,
    eval_ims_per_gpu=16,
    use_fp16=False,
    use_sync_bn=False,
    epochs=300,
    warmup_epochs=3,
    respth='./output',
)
